export const OWNER_REMOVE = "OWNER_REMOVE";
export const ADMIN_REMOVE = "ADMIN_REMOVE";
export const ALREADY_REGISTERED = "ALREADY_REGISTERED";
export const ALREADY_APPROVED = "ALREADY_APPROVED";
export const NOT_APPROVED_YET = "NOT_APPROVED_YET";
export const NOT_REGISTERED_YET = "NOT_REGISTERED_YET";
export const NO_PLATENUMBER_YET = "NO_PLATENUMBER_YET";